In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv(r'R:\PROJECTS\Hypertension Prediction System\HYPERTENSION-PREDICTION\hypertension_dataset.csv')

In [47]:
df

,Age,Salt_Intake,Stress_Score,BP_History,Sleep_Duration,BMI,Medication,Family_History,Exercise_Level,Smoking_Status,Has_Hypertension
0,69,8.0,9,Normal,6.4,25.8,NaN,Yes,Low,Non-Smoker,Yes
1,32,11.7,10,Normal,5.4,23.4,NaN,No,Low,Non-Smoker,No
2,78,9.5,3,Normal,7.1,18.7,NaN,No,Moderate,Non-Smoker,No
3,38,10.0,10,Hypertension,4.2,22.1,ACE Inhibitor,No,Low,Non-Smoker,Yes
4,41,9.8,1,Prehypertension,5.8,16.2,Other,No,Moderate,Non-Smoker,No
...,...,...,...,...,...,...,...,...,...,...,...
1980,56,10.2,0,Normal,6.5,25.0,Diuretic,Yes,Low,Non-Smoker,Yes
1981,29,8.9,4,Hypertension,6.9,16.9,NaN,Yes,High,Non-Smoker,Yes
1982,64,5.9,9,Normal,5.6,18.9,ACE Inhibitor,Yes,Moderate,Non-Smoker,Yes
1983,35,7.4,8,Prehypertension,8.2,29.2,NaN,Yes,Moderate,Non-Smoker,No
1984,38,7.3,0,Normal,8.3,18.6,NaN,Yes,Low,Smoker,No

In [48]:
df.describe()

               Age  Salt_Intake  Stress_Score  Sleep_Duration          BMI
count  1985.000000  1985.000000   1985.000000     1985.000000  1985.000000
mean     50.341058     8.531688      4.979345        6.452242    26.015315
std      19.442042     1.994907      3.142303        1.542207     4.512857
min      18.000000     2.500000      0.000000        1.500000    11.900000
25%      34.000000     7.200000      2.000000        5.400000    23.000000
50%      50.000000     8.500000      5.000000        6.500000    25.900000
75%      67.000000     9.900000      8.000000        7.500000    29.100000
max      84.000000    16.400000     10.000000       11.400000    41.900000

In [49]:
df.columns = df.columns.str.lower()
df.columns

Index(['age', 'salt_intake', 'stress_score', 'bp_history', 'sleep_duration',
       'bmi', 'medication', 'family_history', 'exercise_level',
       'smoking_status', 'has_hypertension'],
      dtype='str')

In [50]:
# HANDLING Null Values
df.isnull().sum()

age                   0
salt_intake           0
stress_score          0
bp_history            0
sleep_duration        0
bmi                   0
medication          799
family_history        0
exercise_level        0
smoking_status        0
has_hypertension      0
dtype: int64

In [51]:
df[df['medication'].isnull()]

,age,salt_intake,stress_score,bp_history,sleep_duration,bmi,medication,family_history,exercise_level,smoking_status,has_hypertension
0,69,8.0,9,Normal,6.4,25.8,NaN,Yes,Low,Non-Smoker,Yes
1,32,11.7,10,Normal,5.4,23.4,NaN,No,Low,Non-Smoker,No
2,78,9.5,3,Normal,7.1,18.7,NaN,No,Moderate,Non-Smoker,No
7,70,5.9,1,Hypertension,7.2,25.8,NaN,No,Moderate,Non-Smoker,Yes
9,47,7.2,5,Normal,6.2,24.3,NaN,No,High,Non-Smoker,No
...,...,...,...,...,...,...,...,...,...,...,...
1975,49,7.7,0,Normal,7.5,17.2,NaN,No,Moderate,Non-Smoker,No
1978,38,7.4,9,Prehypertension,6.2,23.6,NaN,No,Low,Non-Smoker,No
1981,29,8.9,4,Hypertension,6.9,16.9,NaN,Yes,High,Non-Smoker,Yes
1983,35,7.4,8,Prehypertension,8.2,29.2,NaN,Yes,Moderate,Non-Smoker,No
1984,38,7.3,0,Normal,8.3,18.6,NaN,Yes,Low,Smoker,No

In [52]:
df.shape

(1985, 11)

In [53]:
na_pct = df['medication'].isnull().sum() / len(df['medication']) * 100
print(f"Percentage of missing values in 'medication' column: {na_pct:.2f}%")

Percentage of missing values in 'medication' column: 40.25%

In [54]:
df['medication']= df['medication'].fillna('Unknown')

In [55]:
print(df["medication"].value_counts(dropna=False))
print(df["medication"].dtype)
print(df["medication"].unique())
print('\n-------------------------------------------')
print('\nThe column is nominal in nature.')

medication
Unknown          799
Beta Blocker     412
ACE Inhibitor    323
Diuretic         245
Other            206
Name: count, dtype: int64
str
<ArrowStringArray>
['Unknown', 'ACE Inhibitor', 'Other', 'Beta Blocker', 'Diuretic']
Length: 5, dtype: str

-------------------------------------------

The column is nominal in nature.

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1985 non-null   int64
 1   salt_intake       1985 non-null   float64
 2   stress_score      1985 non-null   int64
 3   bp_history        1985 non-null   str
 4   sleep_duration    1985 non-null   float64
 5   bmi               1985 non-null   float64
 6   medication        1985 non-null   str
 7   family_history    1985 non-null   str
 8   exercise_level    1985 non-null   str
 9   smoking_status    1985 non-null   str
 10  has_hypertension  1985 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 244.7 KB

In [57]:
# Analyzing blood pressure history columns
df['bp_history'].value_counts()
print('The column is ordinal in nature.')

The column is ordinal in nature.

In [58]:
print('For Normal BP:', df[df['bp_history']=='Normal']['has_hypertension'].value_counts())
print('For Prehypertension:', df[df['bp_history']=='Prehypertension']['has_hypertension'].value_counts())
print('For Hypertension:', df[df['bp_history']=='Hypertension']['has_hypertension'].value_counts())

For Normal BP: has_hypertension
No     510
Yes    286
Name: count, dtype: int64
For Prehypertension: has_hypertension
No     402
Yes    218
Name: count, dtype: int64
For Hypertension: has_hypertension
Yes    528
No      41
Name: count, dtype: int64

In [59]:
# Checcking family history of hypertension
df['family_history'].value_counts()
print('The column is nominal in nature.')

The column is nominal in nature.

In [60]:
# Analyzing excercise_level column
print(df['exercise_level'].value_counts())
print('The column is ordinal in nature.')

exercise_level
Low         936
Moderate    658
High        391
Name: count, dtype: int64
The column is ordinal in nature.

In [62]:
# Analyzing smoking_status column
print(df['smoking_status'].value_counts())

print('The column is nominal in nature.')

smoking_status
Non-Smoker    1417
Smoker         568
Name: count, dtype: int64
The column is nominal in nature.

In [63]:
# Analyzing has_hypertension column
print(df['has_hypertension'].value_counts())
print('The column is nominal in nature.')

has_hypertension
Yes    1032
No      953
Name: count, dtype: int64
The column is nominal in nature.

## Encoding Features

#### Ordinal Encoding

In [64]:
df.columns

Index(['age', 'salt_intake', 'stress_score', 'bp_history', 'sleep_duration',
       'bmi', 'medication', 'family_history', 'exercise_level',
       'smoking_status', 'has_hypertension'],
      dtype='str')

In [65]:
# Map blood pressure history to numerical values[Normal: 0, Prehypertension: 1, Hypertension: 2 ]
df['bp_history'] = df['bp_history'].map({'Normal': 0, 'Prehypertension': 1, 'Hypertension': 2}) 

# Map family history to numerical values[No: 0, Yes: 1]
df['family_history'] = df['family_history'].map({'No': 0, 'Yes': 1}) 

# Map exercise level to numerical values[Low: 0, Moderate: 1, High: 2]
df['exercise_level'] = df['exercise_level'].map({'Low': 0, 'Moderate': 1, 'High': 2}) 

# Map smoking status to numerical values[Non-smoker: 0, Smoker: 1]
df['smoking_status'] = df['smoking_status'].map({'Non-Smoker': 0, 'Smoker': 1}) 

# Map hypertension status to numerical values[No: 0, Yes: 1]
df['has_hypertension'] = df['has_hypertension'].map({'No': 0, 'Yes': 1})

In [66]:
df

,age,salt_intake,stress_score,bp_history,sleep_duration,bmi,medication,family_history,exercise_level,smoking_status,has_hypertension
0,69,8.0,9,0,6.4,25.8,Unknown,1,0,0,1
1,32,11.7,10,0,5.4,23.4,Unknown,0,0,0,0
2,78,9.5,3,0,7.1,18.7,Unknown,0,1,0,0
3,38,10.0,10,2,4.2,22.1,ACE Inhibitor,0,0,0,1
4,41,9.8,1,1,5.8,16.2,Other,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1980,56,10.2,0,0,6.5,25.0,Diuretic,1,0,0,1
1981,29,8.9,4,2,6.9,16.9,Unknown,1,2,0,1
1982,64,5.9,9,0,5.6,18.9,ACE Inhibitor,1,1,0,1
1983,35,7.4,8,1,8.2,29.2,Unknown,1,1,0,0
1984,38,7.3,0,0,8.3,18.6,Unknown,1,0,1,0

#### Nominal Encoding

In [ ]:
df = pd.get_dummies(df, columns=['medication'], drop_first=True)