In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'R:\PROJECTS\Hypertension Prediction System\HYPERTENSION-PREDICTION\hypertension_dataset.csv')

In [3]:
df

,Age,Salt_Intake,Stress_Score,BP_History,Sleep_Duration,BMI,Medication,Family_History,Exercise_Level,Smoking_Status,Has_Hypertension
0,69,8.0,9,Normal,6.4,25.8,NaN,Yes,Low,Non-Smoker,Yes
1,32,11.7,10,Normal,5.4,23.4,NaN,No,Low,Non-Smoker,No
2,78,9.5,3,Normal,7.1,18.7,NaN,No,Moderate,Non-Smoker,No
3,38,10.0,10,Hypertension,4.2,22.1,ACE Inhibitor,No,Low,Non-Smoker,Yes
4,41,9.8,1,Prehypertension,5.8,16.2,Other,No,Moderate,Non-Smoker,No
...,...,...,...,...,...,...,...,...,...,...,...
1980,56,10.2,0,Normal,6.5,25.0,Diuretic,Yes,Low,Non-Smoker,Yes
1981,29,8.9,4,Hypertension,6.9,16.9,NaN,Yes,High,Non-Smoker,Yes
1982,64,5.9,9,Normal,5.6,18.9,ACE Inhibitor,Yes,Moderate,Non-Smoker,Yes
1983,35,7.4,8,Prehypertension,8.2,29.2,NaN,Yes,Moderate,Non-Smoker,No
1984,38,7.3,0,Normal,8.3,18.6,NaN,Yes,Low,Smoker,No

In [7]:
df.columns = df.columns.str.lower()
df.columns

Index(['age', 'salt_intake', 'stress_score', 'bp_history', 'sleep_duration',
       'bmi', 'medication', 'family_history', 'exercise_level',
       'smoking_status', 'has_hypertension'],
      dtype='str')

In [ ]:
# HANDLING Null Values
df.isnull().sum()

Age                   0
Salt_Intake           0
Stress_Score          0
BP_History            0
Sleep_Duration        0
BMI                   0
Medication          799
Family_History        0
Exercise_Level        0
Smoking_Status        0
Has_Hypertension      0
dtype: int64

In [11]:
df[df['medication'].isnull()]

,age,salt_intake,stress_score,bp_history,sleep_duration,bmi,medication,family_history,exercise_level,smoking_status,has_hypertension
0,69,8.0,9,Normal,6.4,25.8,NaN,Yes,Low,Non-Smoker,Yes
1,32,11.7,10,Normal,5.4,23.4,NaN,No,Low,Non-Smoker,No
2,78,9.5,3,Normal,7.1,18.7,NaN,No,Moderate,Non-Smoker,No
7,70,5.9,1,Hypertension,7.2,25.8,NaN,No,Moderate,Non-Smoker,Yes
9,47,7.2,5,Normal,6.2,24.3,NaN,No,High,Non-Smoker,No
...,...,...,...,...,...,...,...,...,...,...,...
1975,49,7.7,0,Normal,7.5,17.2,NaN,No,Moderate,Non-Smoker,No
1978,38,7.4,9,Prehypertension,6.2,23.6,NaN,No,Low,Non-Smoker,No
1981,29,8.9,4,Hypertension,6.9,16.9,NaN,Yes,High,Non-Smoker,Yes
1983,35,7.4,8,Prehypertension,8.2,29.2,NaN,Yes,Moderate,Non-Smoker,No
1984,38,7.3,0,Normal,8.3,18.6,NaN,Yes,Low,Smoker,No

In [18]:
na_pct = df['medication'].isnull().sum() / len(df['medication']) * 100
print(f"Percentage of missing values in 'medication' column: {na_pct:.2f}%")

Percentage of missing values in 'medication' column: 40.25%

In [25]:
df['medication']= df['medication'].fillna('Unknown')

In [26]:
print(df["medication"].value_counts(dropna=False))
print(df["medication"].dtype)
print(df["medication"].unique())

medication
Unknown          799
Beta Blocker     412
ACE Inhibitor    323
Diuretic         245
Other            206
Name: count, dtype: int64
str
<ArrowStringArray>
['Unknown', 'ACE Inhibitor', 'Other', 'Beta Blocker', 'Diuretic']
Length: 5, dtype: str

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1985 entries, 0 to 1984
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1985 non-null   int64
 1   salt_intake       1985 non-null   float64
 2   stress_score      1985 non-null   int64
 3   bp_history        1985 non-null   str
 4   sleep_duration    1985 non-null   float64
 5   bmi               1985 non-null   float64
 6   medication        1985 non-null   str
 7   family_history    1985 non-null   str
 8   exercise_level    1985 non-null   str
 9   smoking_status    1985 non-null   str
 10  has_hypertension  1985 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 244.7 KB